export enum MediaFormat {
  BOOK__HARDCOVER = "BOOK__HARDCOVER",
  BOOK__PAPERBACK = "BOOK__PAPERBACK",
  MOVIE__BLUERAY = "MOVIE__BLUERAY",
  MOVIE__BLUERAY_DVD_COMBO = "MOVIE__BLUERAY_DVD_COMBO",
  MOVIE__BLUERAY_3D_BLURAY_COMBO = "MOVIE__BLUERAY_3D_BLURAY_COMBO",
  MOVIE__DVD = "MOVIE__DVD",
  MOVIE__VHS = "MOVIE__VHS",
  VIDEO_GAME__PS1 = "VIDEO_GAME__PS1",
  VIDEO_GAME__PS2 = "VIDEO_GAME__PS2",
  VIDEO_GAME__PS3 = "VIDEO_GAME__PS3",
  VIDEO_GAME__PS4 = "VIDEO_GAME__PS4",
  VIDEO_GAME__PS5 = "VIDEO_GAME__PS5",
  VIDEO_GAME__NES = "VIDEO_GAME__NES",
  VIDEO_GAME__N64 = "VIDEO_GAME__N64",
  VIDEO_GAME__SWITCH = "VIDEO_GAME__SWITCH",
  VIDEO_GAME__GAMECUBE = "VIDEO_GAME__GAMECUBE",
  VIDEO_GAME__WII = "VIDEO_GAME__WII",
  VIDEO_GAME__PC = "VIDEO_GAME__PC",
  VIDEO_GAME__XBOX = "VIDEO_GAME__XBOX",
  VIDEO_GAME__XBOX_360 = "VIDEO_GAME__XBOX_360",
  WISH_LIST__BOOK = "WISH_LIST__BOOK",
  WISH_LIST__MOVIE = "WISH_LIST__MOVIE",
  WISH_LIST__VIDEO_GAME = "WISH_LIST__VIDEO_GAME",
}

export enum ListFilter {
  BOOK = "BOOK",
  MOVIE = "MOVIE",
  VIDEO_GAME = "VIDEO_GAME",
  WISH_LIST__BOOK = "WISH_LIST__BOOK",
  WISH_LIST__MOVIE = "WISH_LIST__MOVIE",
  WISH_LIST__VIDEO_GAME = "WISH_LIST__VIDEO_GAME",
}

export enum MovieFormat {
  BLUERAY = "BLUERAY",
  BLUERAY_DVD_COMBO = "BLUERAY_DVD_COMBO",
  MOVIE__BLUERAY_3D_BLURAY_COMBO = "MOVIE__BLUERAY_3D_BLURAY_COMBO",
  DVD = "DVD",
  VHS = "VHS",
}

export enum VideoGameFormat {
  PS1 = "PS1",
  PS2 = "PS2",
  PS3 = "PS3",
  PS4 = "PS4",
  PS5 = "PS5",
  NES = "NES",
  N64 = "N64",
  SWITCH = "SWITCH",
  GAMECUBE = "GAMECUBE",
  WII = "WII",
  PC = "PC",
  XBOX = "XBOX",
  XBOX_360 = "XBOX_360",
}
